name: "mendigo-chato"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro 
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend/.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
      - PORT=3000 
      - DATABASE_URL=postgresql://viddy:L4ILcP86PHY4mzKe7IWOVhX3R0Eqvb1eM5EUpVyHCbOcv@pg:5432/vidify
      - REDIS_URL=redis://redis:6379
    depends_on:
      - pg
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  pg:
    image: bitnami/postgresql:latest
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=viddy
      - POSTGRES_PASSWORD=L4ILcP86PHY4mzKe7IWOVhX3R0Eqvb1eM5EUpVyHCbOcv
      - POSTGRES_DB=vidify
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      retries: 5

volumes:
  postgres_data: