name: "vidify"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vidify
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
 