export const suggestions: string[] = [
  "Top 5 coisas mais caras do mundo",
  "Coisas mais raras do mundo",
  "Coisas mais estranhas encontradas na natureza",
  "Coisas mais antigas já descobertas",
  "Coisas mais pequenas do universo",
  "Coisas mais rápidas já construídas",
  "Coisas mais grandes do mundo",
  "Coisas mais tecnológicas do mercado",
  "Coisas mais perigosas do planeta",
  "Coisas mais misteriosas do oceano",
  "Coisas mais assustadoras da internet",
  "Coisas mais engraçadas já vistas",
  "Coisas mais loucas feitas por humanos",
  "Coisas mais incríveis da ciência",
  "Coisas mais inovadoras da tecnologia",
  "Coisas mais estranhas do espaço",
  "Coisas mais curiosas sobre animais",
  "Coisas mais belas da natureza",
  "Coisas mais extraordinárias encontradas",
  "Coisas mais incríveis do mundo antigo",
  "Coisas mais valiosas descobertas",
  "Coisas mais secretas do governo",
  "Coisas mais estranhas já vendidas",
  "Coisas mais misteriosas da história",
  "Coisas mais incríveis feitas por crianças",
  "Coisas mais únicas encontradas em casas",
  "Coisas mais brilhantes do universo",
  "Coisas mais interessantes sobre culturas",
  "Coisas mais antigas feitas por humanos",
  "Coisas mais fascinantes sobre o cérebro",
  "Coisas mais incomuns na culinária",
  "Coisas mais raras sobre plantas",
  "Coisas mais inacreditáveis vistas no esporte",
  "Coisas mais aterrorizantes sobre fantasmas",
  "Coisas mais estranhas sobre moda",
  "Coisas mais malucas sobre celebridades",
  "Coisas mais curiosas sobre o corpo humano",
  "Coisas mais inusitadas sobre invenções",
  "Coisas mais fantásticas de contos de fadas",
  "Coisas mais intrigantes sobre o futuro",
  "Coisas mais difíceis de acreditar que existem",
  "Coisas mais surpreendentes sobre a música",
  "Coisas mais inusitadas sobre veículos",
  "Coisas mais fascinantes sobre a água",
  "Coisas mais bizarras sobre alimentos",
  "Coisas mais espetaculares sobre festivais",
  "Coisas mais intrigantes sobre mitologia",
  "Coisas mais surpreendentes sobre o tempo",
  "Coisas mais incríveis sobre a matemática",
  "Receitas de pratos internacionais",
  "Dicas de viagem para destinos exóticos",
  "Histórias inspiradoras de superação",
  "Filmes clássicos que marcaram época",
  "Livros que mudaram vidas",
  "Curiosidades sobre culturas indígenas",
  "Histórias engraçadas de família",
  "Mitos e lendas urbanas famosas",
  "Dicas de organização pessoal",
  "Experiências gastronômicas únicas",
  "Técnicas de fotografia para iniciantes",
  "Rotinas de exercícios para saúde mental",
  "Dicas para economizar dinheiro",
  "Arte de rua mais impressionante do mundo",
  "Histórias incríveis de amizade",
  "Arquitetura futurista ao redor do globo",
  "Ideias de negócios inovadores",
  "Curiosidades sobre idiomas diferentes",
  "Tradições de casamento ao redor do mundo",
  "Músicas que definem uma geração",
  "Danças folclóricas de várias culturas",
  "Tendências de moda ao longo dos anos",
  "Curiosidades sobre esportes olímpicos",
  "Festivais de música únicos",
  "Jardins botânicos mais bonitos",
  "Criaturas míticas de diferentes culturas",
  "Avanços científicos recentes",
  "Dicas para cuidar de animais de estimação",
  "Histórias fascinantes de descobertas arqueológicas",
  "Artistas contemporâneos que você deveria conhecer",
  "Esculturas mais impressionantes do mundo",
  "Curiosidades sobre fenômenos naturais",
  "Tradições de celebração de Ano Novo",
  "Jogos de tabuleiro clássicos",
  "Tecnologias emergentes no setor automotivo",
  "Histórias de coragem de pessoas famosas",
  "Experiências de voluntariado transformadoras",
  "Grandes feitos da engenharia moderna",
  "Documentários que mudaram percepções",
  "Histórias de amor inspiradoras",
  "Curiosidades sobre astronomia",
  "Curiosidades sobre o universo dos games",
  "Artigos científicos mais impactantes",
  "Experiências imersivas de realidade virtual",
  "Destinos de ecoturismo incríveis",
  "Artes marciais e suas filosofias",
  "Curiosidades sobre dinossauros",
  "Invenções que revolucionaram o mundo",
  "Histórias de sucesso de startups",
  "Curiosidades sobre o sistema solar",
  "Descobertas recentes na medicina",
  "Experiências culturais em grandes cidades",
  "Momentos históricos que mudaram o mundo",
  "Curiosidades sobre fenômenos sobrenaturais",
  "Técnicas de relaxamento e meditação",
  "Descobertas mais fascinantes da biologia",
  "Artigos de moda icônicos",
  "Histórias de heróis desconhecidos",
  "Tecnologias verdes e sustentáveis",
  "Curiosidades sobre aviação",
  "Tendências de design de interiores",
  "Casas mais incríveis do mundo",
  "Histórias de crimes resolvidos com tecnologia",
  "Curiosidades sobre o sistema judicial",
  "Marcas icônicas de moda",
  "Revoluções na indústria alimentícia",
  "Histórias de grandes exploradores",
  "Tecnologias emergentes na educação",
  "Pinturas mais famosas da história",
  "Curiosidades sobre o sistema financeiro",
  "Invenções caseiras geniais",
  "Tradições culinárias familiares",
  "Histórias de grandes epidemias superadas",
  "Curiosidades sobre terremotos e vulcões",
  "Descobertas mais estranhas da história",
  "Arte corporal ao redor do mundo",
  "Histórias de sobrevivência em condições extremas",
  "Tradições de Natal ao redor do mundo",
  "Curiosidades sobre energias renováveis",
  "Desafios científicos não resolvidos",
  "Filosofias de vida inspiradoras",
  "Descobertas arqueológicas controversas",
  "Curiosidades sobre inteligência artificial",
  "Tradições de celebração de casamento",
  "Momentos históricos esquecidos",
  "Curiosidades sobre tecnologia espacial",
  "Invenções esquecidas que merecem reconhecimento",
  "Histórias de grandes músicos de rua",
  "Curiosidades sobre fenômenos meteorológicos",
  "Estilos de dança únicos ao redor do mundo",
  "Descobertas incríveis da psicologia",
  "Curiosidades sobre a vida marinha",
  "Tradições de festivais de outono",
  "Grandes avanços na neurociência",
  "Curiosidades sobre a história da moda",
  "Momentos históricos de cooperação internacional",
  "Descobertas mais estranhas da ciência",
  "Curiosidades sobre epidemias históricas",
  "Invenções revolucionárias na medicina",
  "Histórias de grandes bibliotecas ao redor do mundo",
];
