export const suggestions = [
  "Top 5 coisas mais caras do mundo",
  "Coisas mais raras do mundo",
  "Coisas mais estranhas encontradas na natureza",
  "Coisas mais antigas já descobertas",
  "Coisas mais pequenas do universo",
  "Coisas mais rápidas já construídas",
  "Coisas mais grandes do mundo",
  "Coisas mais tecnológicas do mercado",
  "Coisas mais perigosas do planeta",
  "Coisas mais misteriosas do oceano",
  "Coisas mais assustadoras da internet",
  "Coisas mais engraçadas já vistas",
  "Coisas mais loucas feitas por humanos",
  "Coisas mais incríveis da ciência",
  "Coisas mais inovadoras da tecnologia",
  "Coisas mais estranhas do espaço",
  "Coisas mais curiosas sobre animais",
  "Coisas mais belas da natureza",
  "Coisas mais extraordinárias encontradas",
  "Coisas mais incríveis do mundo antigo",
  "Coisas mais valiosas descobertas",
  "Coisas mais secretas do governo",
  "Coisas mais estranhas já vendidas",
  "Coisas mais misteriosas da história",
  "Coisas mais incríveis feitas por crianças",
  "Coisas mais únicas encontradas em casas",
  "Coisas mais brilhantes do universo",
  "Coisas mais interessantes sobre culturas",
  "Coisas mais antigas feitas por humanos",
  "Coisas mais fascinantes sobre o cérebro",
  "Coisas mais incomuns na culinária",
  "Coisas mais raras sobre plantas",
  "Coisas mais inacreditáveis vistas no esporte",
  "Coisas mais aterrorizantes sobre fantasmas",
  "Coisas mais estranhas sobre moda",
  "Coisas mais malucas sobre celebridades",
  "Coisas mais curiosas sobre o corpo humano",
  "Coisas mais inusitadas sobre invenções",
  "Coisas mais fantásticas de contos de fadas",
  "Coisas mais intrigantes sobre o futuro",
  "Coisas mais difíceis de acreditar que existem",
  "Coisas mais surpreendentes sobre a música",
  "Coisas mais inusitadas sobre veículos",
  "Coisas mais fascinantes sobre a água",
  "Coisas mais bizarras sobre alimentos",
  "Coisas mais espetaculares sobre festivais",
  "Coisas mais intrigantes sobre mitologia",
  "Coisas mais surpreendentes sobre o tempo",
  "Coisas mais incríveis sobre a matemática",
];
